### ISSUE TITLE
Configuration Recommendation for usage with AudioWorklet

### ISSUE THREAD

**Issue by mulder999** [richardtallent/vite-plugin-singlefile#88] opened 2024-01-18 15:32 UTC
The method [AudioContext.audioWorklet.addModule](https://developer.mozilla.org/en-US/docs/Web/API/Worklet/addModule) seems to mandate an external file.

Hence I am seeking recommendations on how to configure Vite and ViteSingleFile plugin to support this specific usage.

Thank you in advance for your support.

**Comment by richardtallent** [comment] 2024-01-30 02:24
If you can provide a minimal reproduction, it's possible I or someone more familiar with that API could take a look.

Taking a wild guess, your best bet is probably using a data URL:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs

**Comment by richardtallent** [comment] 2024-06-20 03:59
Closing due to lack of reproduction / detail

**Closed by richardtallent** 2024-06-20 03:59 UTC
Labels: enhancement
