### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module ...\node_modules\vite-plugin-singlefile\dist\index.js from ...\vite.config.js not supported.

### ISSUE THREAD

**Issue by conanliuhuan** [richardtallent/vite-plugin-singlefile#33] opened 2022-06-06 06:52 UTC
![Snipaste_2022-06-06_14-51-51](https://user-images.githubusercontent.com/26618275/172110542-df5ac169-ba10-48ba-b50e-e48d85edefaa.png)

**Comment by zhanglongqi** [comment] 2022-06-06 08:11
add `"type": "module",` to your `package.json`

**Comment by tony19** [comment] 2022-06-07 01:06
Duplicate of #23

A [workaround](https://github.com/richardtallent/vite-plugin-singlefile/issues/23#issuecomment-1057287278) is to install 0.7.1:

```shell
npm i -D vite-plugin-singlefile@0.7.1
```

**Comment by richardtallent** [comment] 2022-06-15 02:22
Please try 0.10.0-beta and let me know if it helps. It *should* allow use in both CommonJS and ESM environments.

**Comment by pitw** [comment] 2022-06-27 08:00
Got same error; With 0.10.0-beta it works 👍

**Comment by richardtallent** [comment] 2022-07-01 15:14
0.10.0 has been released,

**Closed by richardtallent** 2022-07-01 15:14 UTC
Labels: enhancement
